function renderMovie(filename, name) {
    const li = document.createElement('li')

    const image = document.createElement('img')
    const src = document.createAttribute("src");
    src.value = "./movies/" + filename + "_min.jpg"
    image.setAttributeNode(src)

    const a = document.createElement('a')
    const href = document.createAttribute("href");
    href.value = "./movies/" + filename + ".jpg"
    a.setAttributeNode(href)
    a.appendChild(image)

    const caption = document.createElement('figcaption')
    caption.textContent = name

    const figure = document.createElement('figure')
    figure.appendChild(a)
    figure.appendChild(caption)

    li.appendChild(figure)

    const ul = document.querySelector('ul');
    ul.appendChild(li)
}

renderMovie("9_pisem_odnogo_goda", "9 писем одного года")
renderMovie("adaline", "Век адалин")
renderMovie("angryredplanet1","Грозная красная планета")
renderMovie("angryredplanet2","Грозная красная планета")
renderMovie("angryredplanet3","Грозная красная планета")
renderMovie("amerikanskiy_psihopat", "Американский психопат")
renderMovie("armageddon", "Армагеддон")
renderMovie("batman_robin", "Бэтмен и Робин")
renderMovie("body_double", "Двойник тела")
renderMovie("beach_party", "Пляжная вечеринка")
renderMovie("bogatenjkiy_rich", "Богатенький Ричи")
renderMovie("bogatenjkiy_rich1", "Богатенький Ричи")
renderMovie("blizkie_kontakty", "Близкие контакты третьей степени")
renderMovie("bratjya_iz_grimsbi", "Братья из Гримсби")
renderMovie("bttf3", "Назад в будущее 3")
renderMovie("bukiny", "Букины")
renderMovie("brainstorm", "Мозговой штурм")
renderMovie("bond_never_say_never_again", "Джеймс Бонд: Никогда не говори никогда")
renderMovie("castle4x06", "Касл 4х06")
renderMovie("dawnofthedead", "Рассвет мертвецов")
renderMovie("dayofthesiege", "Одиннадцатое сентября 1683 года")
renderMovie("dennis_menace_innocents_from_space", "Деннис-непоседа. Невинные из космоса")
renderMovie("deathday", "Счастливого дня смерти")
renderMovie("deep_impact", "Глубокое столкновение")
renderMovie("deep_impact_2", "Глубокое столкновение")
renderMovie("doctor_who_partners_in_crime", "Доктор Кто: Соучастники")
renderMovie("doctor_who_the_moonbase", "Доктор Кто: Лунная база")
renderMovie("dontlookup", "Не смотрите наверх")
renderMovie("dontlookup2", "Не смотрите наверх")
renderMovie("doktor_kto", "Доктор Кто")
renderMovie("dzhango", "Джанго освобожденный")
renderMovie("escape_plan", "План побега")
renderMovie("elevation1", "Хищные земли")
renderMovie("elevation2", "Хищные земли")
renderMovie("einstein_eddington", "Эйнштейн и Эддингтон")
renderMovie("fontan", "Фонтан")
renderMovie("furiosa", "Фуриоса: Хроники Безумного Макса")
renderMovie("geostorm", "Геошторм")
renderMovie("ghostandmrsmuir", "Призрак и миссис Мьюр")
renderMovie("grinch", "Гринч")
renderMovie("gods_must_be_crazy", "Наверное, боги сошли с ума")
renderMovie("harper", "Харпер")
renderMovie("harrigan", "Телефон мистера Харригана")
renderMovie("heroes_s03e07", "Герои s03e07")
renderMovie("hotshots", "Горячие головы")
renderMovie("housewives", "Отчаянные домохозяйки")
renderMovie("inoplanetnoe_vtorzhenie", "Инопланетное вторжение")
renderMovie("invaders_from_mars", "Пришельцы с Марса")
renderMovie("invisible_ray", "Невидимый луч")
renderMovie("insidious", "Астрал")
renderMovie("izgoy", "Изгой")
renderMovie("judge", "Судья")
renderMovie("jurassic_park2", "Парк Юрского периода 2")
renderMovie("kronos", "Хронос")
renderMovie("ka_peks", "Планета Ка-Пэкс")
renderMovie("klaustrofoby2", "Клаустрофобы 2")
renderMovie("kontakt", "Контакт")
renderMovie("kundun", "Кундун")
renderMovie("local_hero", "Местный герой")
renderMovie("local_hero2", "Местный герой")
renderMovie("little_ceasars", "Реклама Little Caesar")
renderMovie("k_chertu_lyubov", "К черту любовь")
renderMovie("lady_hamilton", "Леди Гамильтон")
renderMovie("luca", "Лука")
renderMovie("machete_ubivaet", "Мачете убивает")
renderMovie("magical_mystery_tour", "Волшебное таинственное путешествие")
renderMovie("mastercommander", "Хозяин морей: На краю земли")
renderMovie("men_into_space_ep12", "Men into space ep12")
renderMovie("men_into_space_ep12_1", "Men into space ep12")
renderMovie("melanholiya", "Меланхолия")
renderMovie("mission_to_mars", "Миссия на Марс")
renderMovie("moonlighting1x06", "Детективное агенство: Лунный свет")
renderMovie("mib2", "Люди в черном 2")
renderMovie("moonfall", "Падение Луны")
renderMovie("movie43", "Муви 43")
renderMovie("my_tutor", "Мой наставник")
renderMovie("naprolom", "Напролом")
renderMovie("nevozmozhnoe_2012", "Невозможное")
renderMovie("odin_doma_3", "Один дома 3")
renderMovie("office_s7deleted", "Офис. Удаленные сцены")
renderMovie("angels_wings", "Только у ангелов есть крылья")
renderMovie("parizh", "Париж")
renderMovie("pirates3", "Пираты Карибского моря 3")
renderMovie("pomni_voskresenje", "Помни воскресенье")
renderMovie("pomni_voskresenje_2", "Помни воскресенье")
renderMovie("po_tu_storonu_dveri", "По ту сторону двери")
renderMovie("poltergeist", "Полтергейст")
renderMovie("prestige", "Престиж")
renderMovie("pribytie", "Прибытие")
renderMovie("prosti_za_lyubov", "Прости за любовь")
renderMovie("pro_krasnuyu_shapochku", "Про красную шапочку")
renderMovie("pyatyy_element", "Пятый элемент")
renderMovie("raven", "Ворон")
renderMovie("reklama_twix", "Реклама твикс")
renderMovie("robin_hood", "Робин Гуд")
renderMovie("roxanne", "Роксанна")
renderMovie("sashatanya12", "СашаТаня")
renderMovie("sabrina1x16", "Сабрина")
renderMovie("scream2022", "Крик")
renderMovie("scrooged", "Новая рождественская сказка")
renderMovie("seks_po_druzhbe", "Секс по дружбе")
renderMovie("seks_po_druzhbe_2", "Секс по дружбе")
renderMovie("sherlok_3_seriya", "Шерлок. 3 серия")
renderMovie("sindbadadventures42", "Приключения Синдбада")
renderMovie("sinjor_robinzon", "Синьор Робинзон")
renderMovie("skrytyy_vrag", "Скрытый враг")
renderMovie("skyline", "Скайлайн")
renderMovie("sky_trackers", "Звездные странники")
renderMovie("slepaya_yarostj", "Слепая ярость")
renderMovie("smoking", "Смокинг")
renderMovie("sobaka_baskerviley", "Собака Баскервиллей")
renderMovie("somelikeithot", "В джазе только девушки")
renderMovie("speshi_lyubitj", "Спеши любить")
renderMovie("star_trek_first_contact", "Звездный путь: первый контакт")
renderMovie("stardust", "Звездная пыль")
renderMovie("star_trek_the_next_generation", "Звездный путь: следующее поколение")
renderMovie("sverhyestestvennoe", "Сверхъестественное")
renderMovie("tayna_doma_s_chasami", "Тайна дома с часами")
renderMovie("tayny_smolvilya", "Тайны Смолвилля")
renderMovie("teoriya_boljshogo_vzryva", "Теория большого взрыва")
renderMovie("the_beach_girls", "The Beach Girls")
renderMovie("the_mechanic", "Механик")
renderMovie("tor", "Тор")
renderMovie("tomb_raider", "Лара Крофт: Расхитительница гробниц")
renderMovie("thomas_crown_affair", "Афера Томаса Крауна")
renderMovie("tupoy_i_eche_tupee", "Тупой и еще тупее")
renderMovie("twinpeaks2x12", "Твин Пикс 2х12")
renderMovie("ubey_menya_tri_raza", "Убей меня три раза")
renderMovie("ventura", "Эйс Вентура 2")
renderMovie("venom3", "Веном 3")
renderMovie("vid_sverhu_luchshe", "Вид сверху лучше")
renderMovie("voshozhdenie_yupiter", "Восхождение Юпитера")
renderMovie("vo_vse_tyazhkie", "Во все тяжкие")
renderMovie("waywayout", "Далеко-далеко")
renderMovie("wolfman", "Челвек-волк")
renderMovie("iseeyou", "В тихом омуте")
renderMovie("wick", "Джон Уик")
renderMovie("x_files_sezon_11_seriya_5", "Секретные материалы s11e05")
renderMovie("x15", "X15")
renderMovie("zheleznyy_chelovek", "Железный человек")
renderMovie("zheleznyy_chelovek_2", "Железный человек")
renderMovie("zheleznyy_chelovek_3", "Железный человек")
renderMovie("znaki", "Знаки")
renderMovie("znamenie", "Знамение")

/*

<li>
                <figure>
                    <a href="./movies/office_s7deleted.jpg">
                        <img src="./movies/office_s7deleted_min.jpg">
                    </a>
                    <figcaption>Офис. Удаленные сцены</figcaption>
                </figure>
            </li>


*/